"""
Manually patch missing abstracts found via web search.
Run once: python3 patch_abstracts.py
"""
import json

PATCHES = {
    "https://doi.org/10.1287/mnsc.2022.03132": (
        "Statistical arbitrage exploits temporal price differences between similar assets. "
        "We develop a comprehensive conceptual framework for statistical arbitrage and a novel "
        "data-driven solution. We construct arbitrage portfolios of similar assets as residual "
        "portfolios from conditional latent asset pricing factors, extract their time-series "
        "signals with a convolutional transformer, and form an optimal trading policy that "
        "maximizes risk-adjusted returns under constraints. Our empirical study on daily U.S. "
        "equities shows a high compensation for arbitrageurs to enforce the law of one price. "
        "Our arbitrage strategies obtain considerable out-of-sample mean returns and Sharpe "
        "ratios, and outperform all benchmark approaches."
    ),
    "https://doi.org/10.1287/mnsc.2021.4025": (
        "We experimentally investigate the attraction effect and compromise effect in bargaining—"
        "a tendency for bargainers to agree to an intermediate option or to an option that "
        "dominates another in an unstructured bargaining environment with commonly known money "
        "payoffs. We find significant attraction and compromise effects, but these are mediated "
        "by the efficiency and equality properties of the feasible agreements. Due to the allure "
        "of equality, the effects are harder to observe when an equal earnings contract is "
        "available. Decoys are more effective in shifting agreements from a very unequal "
        "contract to a less unequal one than the reverse."
    ),
    "https://doi.org/10.1287/mnsc.2021.04059": (
        "We study assortment optimization problems where the goal is to find an assortment that "
        "maximizes a firm's worst-case expected revenue under all ranking-based choice models "
        "consistent with historical sales data generated by past assortments. We establish that "
        "these robust optimization problems can be solved in polynomial time or reformulated as "
        "compact mixed-integer optimization problems. We prove that optimal assortments have a "
        "structure closely related to revenue-ordered assortments."
    ),
    "https://doi.org/10.1287/mnsc.2022.4526": (
        "In a finitely repeated game with asymmetric information, we experimentally examine how "
        "individuals adapt the nature of their lies when settings allow for reputation building. "
        "Although some lies can be detected ex post by the uninformed party, others remain "
        "deniable. We find that traditional market mechanisms, such as reputation, generate "
        "strong changes in the way people lie and lead to strategies in which individuals "
        "maintain plausible deniability—people simply hide their lies better by substituting "
        "deniable lies for detectable lies. Our results highlight the limitations of reputation "
        "to root out fraud when a deniable lie strategy is available."
    ),
    "https://doi.org/10.1287/mnsc.2021.02709": (
        "We present the first systematic approach to detect fake transactions on cryptocurrency "
        "exchanges by exploiting robust statistical and behavioral regularities associated with "
        "authentic trading. We develop a suite of statistical tests and apply them to 29 "
        "cryptocurrency exchanges, finding that wash trading is prevalent and highly concentrated "
        "among unregulated exchanges."
    ),
    "https://doi.org/10.1287/mnsc.2022.4649": (
        "We study the effectiveness of two reward mechanisms—all-or-nothing and piece-rate—to "
        "incentivize full completion of repeated tasks over time. We show theoretically and "
        "confirm experimentally that all-or-nothing bonuses outperform piece-rate incentives "
        "in eliciting perseverance when agents have present-biased preferences, because the "
        "all-or-nothing structure makes early quitting particularly costly."
    ),
    "https://doi.org/10.1287/opre.2021.2215": (
        "In nonparametric contextual bandit formulations, a key complexity driver is the "
        "smoothness of payoff functions with respect to covariates. In practice, smoothness is "
        "typically unknown, and misspecification may severely deteriorate performance of existing "
        "methods. We study when and how algorithms may adapt to unknown smoothness. We first "
        "establish that adapting to unknown smoothness is, in general, impossible. However, "
        "under a self-similarity condition, adaptation is possible, and we develop algorithms "
        "that achieve near-optimal regret without knowledge of the smoothness parameter."
    ),
    "https://doi.org/10.1287/opre.2023.2461": (
        "We propose a new approach for solving stochastic optimal stopping problems by using "
        "simulation to construct a robust optimization problem that approximates the original "
        "to arbitrary accuracy, then solving it to obtain near-optimal Markovian stopping rules. "
        "We characterize the structure of optimal stopping rules and leverage this to develop an "
        "exact reformulation as a zero-one bilinear program over totally unimodular constraints. "
        "Numerical experiments demonstrate that our algorithms outperform state-of-the-art "
        "simulation-based methods on high-dimensional option pricing problems."
    ),
    "https://doi.org/10.1287/opre.2023.2442": (
        "We study a pure-exchange incomplete-market economy with heterogeneous agents who choose "
        "savings, consumption quantity, and consumption bundle while facing fluctuating endowments. "
        "We extend general equilibrium results to a Bewley-type economy with many consumption "
        "goods, showing that under mild conditions aggregate demand depends only on relative "
        "prices. When agents have CES utility with elasticity of substitution ≥ 1, the "
        "competitive stationary equilibrium is unique, and higher endowment inequality decreases "
        "the equilibrium interest rate without changing goods prices."
    ),
    "https://openalex.org/W3213314957": (
        "We study a risk-averse newsvendor problem where demand distribution is unknown and "
        "only historical demand data of related products is available. We use machine learning "
        "methods to weight similarity between the new product and previous ones based on "
        "covariates. The data-driven solution entails a closed-form quantile structure and can "
        "be efficiently computed. The value-at-risk constraint plays a regularizing role, "
        "mitigating sampling error and model misspecification in data-driven decision-making."
    ),
}

papers = json.load(open("papers.json"))
patched = 0
for p in papers:
    if p["doi"] in PATCHES and not p.get("abstract"):
        p["abstract"] = PATCHES[p["doi"]]
        patched += 1

with open("papers.json", "w", encoding="utf-8") as f:
    json.dump(papers, f, ensure_ascii=False, indent=2)

print(f"Patched {patched} abstracts.")
